"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def cum_fib():
    a, b = 1, 1
    cumSum = 0
    while True:
        a, b = b, a + b
        if a % 2 == 0:
            cumSum += a
        if a > 4000000:
            return cumSum


if __name__ == "__main__":
    print(cum_fib())